name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven and Cobertura
        run: mvn -B clean cobertura:cobertura

      - name: Install cobertura-coverage-report
        run: npm install -g cobertura-coverage-report

      - name: Convert Cobertura XML to Coveralls JSON
        run: cobertura-coverage-report --format coveralls target/site/cobertura/coverage.xml

      - name: Upload to Coveralls
        run: curl -F 'json_file=@coveralls.json' https://coveralls.io/api/v1/jobs